language: 
  - cpp

compiler:
  - clang
  - gcc

script:
  - cd ~/build/martinmoene/expected-lite/test
  - $CXX -Wall -Wextra -std=c++11 -Wno-unused-parameter -Dlest_FEATURE_AUTO_REGISTER=1 -I../include/nonstd -o expected.t expected.t.cpp && ./expected.t && ./expected.t --list-tests
