version: '1.0.{build}'

os: 
    - Visual Studio 2015
    - Visual Studio 2017

platform:
    - Win32
    - x64

configuration:
    - Debug
    - Release

before_build:
    - mkdir build
    - cmake -H. -Bbuild -A %platform%

build:
    project: build\expected_lite.sln
    parallel: true
    verbosity: normal     # MSBuild verbosity level {quiet|minimal|normal|detailed}

test_script:
    - cd build
    - ctest -V -j 2 -C %CONFIGURATION%
